In [23]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [3]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

# 无量纲化

In [4]:
##########
#归一化
##########
scalar = MinMaxScaler()
scalar = scalar.fit(data)
ret = scalar.transform(data)
ret

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [5]:
scalar.fit_transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
scalar.inverse_transform(ret)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [9]:
#numpy实现scalar
data = np.array(data)
(data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [11]:
###############
#标准化
################
from sklearn.preprocessing import StandardScaler

standScaler = StandardScaler()
ret = standScaler.fit_transform(data)


In [13]:
ret.mean()

0.0

# 缺失值处理

In [4]:
from sklearn.impute import SimpleImputer

In [3]:
#数据
data_ = pd.DataFrame({'age': [10, 20, None, 25, 30, 35, None, 23, 60, 30], 'servived': [0, 1, 1, 1, 1, 1, 0, 1, 0, 1]})
data_

age  servived
0  10.0         0
1  20.0         1
2   NaN         1
3  25.0         1
4  30.0         1
5  35.0         1
6   NaN         0
7  23.0         1
8  60.0         0
9  30.0         1

In [8]:
data_.loc[:, 'age'].values.reshape(-1, 1)

array([[10.],
       [20.],
       [nan],
       [25.],
       [30.],
       [35.],
       [nan],
       [23.],
       [60.],
       [30.]])

In [9]:
imp_mean = SimpleImputer(strategy="mean")
imp_median = SimpleImputer(strategy="median")
imp_constant = SimpleImputer(strategy="constant", fill_value=22)

In [10]:
imp_mean.fit_transform(data_)

array([[10.   ,  0.   ],
       [20.   ,  1.   ],
       [29.125,  1.   ],
       [25.   ,  1.   ],
       [30.   ,  1.   ],
       [35.   ,  1.   ],
       [29.125,  0.   ],
       [23.   ,  1.   ],
       [60.   ,  0.   ],
       [30.   ,  1.   ]])

In [11]:
imp_median.fit_transform(data_)

array([[10. ,  0. ],
       [20. ,  1. ],
       [27.5,  1. ],
       [25. ,  1. ],
       [30. ,  1. ],
       [35. ,  1. ],
       [27.5,  0. ],
       [23. ,  1. ],
       [60. ,  0. ],
       [30. ,  1. ]])

In [12]:
imp_constant.fit_transform(data_)

array([[10.,  0.],
       [20.,  1.],
       [22.,  1.],
       [25.,  1.],
       [30.,  1.],
       [35.,  1.],
       [22.,  0.],
       [23.,  1.],
       [60.,  0.],
       [30.,  1.]])

## 采用pandas实现

In [14]:
data_.loc[:, 'age'] = data_.loc[:, 'age'].fillna(value=data_.loc[:, 'age'].mean(axis=0), axis=0)


In [15]:
data_

age  servived
0  10.000         0
1  20.000         1
2  29.125         1
3  25.000         1
4  30.000         1
5  35.000         1
6  29.125         0
7  23.000         1
8  60.000         0
9  30.000         1

# 编码和哑变量

In [18]:
#导入模块
from sklearn.preprocessing import LabelEncoder

In [19]:
#数据集
data_code = pd.DataFrame({'age': [22.0, 38.0, 26.0, 35.0], 
			  'sex': ['male', 'female', 'female', 'female'], 
			  'survived': ['No', 'Yes', 'Yes', 'Yes']})
data_code.head()


age     sex survived
0  22.0    male       No
1  38.0  female      Yes
2  26.0  female      Yes
3  35.0  female      Yes

In [21]:
#提取标签值
y = data_code.iloc[:, -1]
y

0     No
1    Yes
2    Yes
3    Yes
Name: survived, dtype: object

In [25]:
#
encoder = LabelEncoder()
data_code.iloc[:, -1] =  encoder.fit_transform(y)

In [26]:
data_code

age     sex  survived
0  22.0    male         0
1  38.0  female         1
2  26.0  female         1
3  35.0  female         1

In [27]:
from sklearn.preprocessing import OrdinalEncoder


In [30]:
data_code.iloc[:, 1].values.reshape(-1, 1)

array([['male'],
       ['female'],
       ['female'],
       ['female']], dtype=object)

In [31]:
data_code.iloc[:, 1] = OrdinalEncoder(dtype=np.int32).fit_transform(data_code.iloc[:, 1].values.reshape(-1, 1))
data_code

age  sex  survived
0  22.0    1         0
1  38.0    0         1
2  26.0    0         1
3  35.0    0         1

## 独热码

In [4]:
from sklearn.preprocessing import OneHotEncoder


In [5]:
#数据集
data_hot = pd.DataFrame({'age': [22.0, 38.0, 26.0, 35.0], 
			  'sex': ['male', 'female', 'female', 'female'], 
			  'embarked': ['S', 'C', 'S', 'S'],
			  'survived': ['No', 'Yes', 'Yes', 'Yes']})

data_hot.head()


age     sex embarked survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes

In [6]:
data_hot.iloc[:, 1: -1]

sex embarked
0    male        S
1  female        C
2  female        S
3  female        S

In [7]:
encoder = OneHotEncoder()
label = encoder.fit_transform(data_hot.iloc[:, 1: -1]).toarray()
label

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [8]:
encoder.get_feature_names()

array(['x0_female', 'x0_male', 'x1_C', 'x1_S'], dtype=object)

In [14]:
joint_data = pd.concat([data_hot, pd.DataFrame(label)], axis=1)
joint_data

age     sex embarked survived    0    1    2    3
0  22.0    male        S       No  0.0  1.0  0.0  1.0
1  38.0  female        C      Yes  1.0  0.0  1.0  0.0
2  26.0  female        S      Yes  1.0  0.0  0.0  1.0
3  35.0  female        S      Yes  1.0  0.0  0.0  1.0

In [20]:
joint_data.columns=['age', 'sex', 'embarked', 'survived', 'x0_female', 'x0_male', 'x1_C', 'x1_S']
joint_data.drop(columns=['sex', 'embarked'], inplace=True)

In [21]:
joint_data

age survived  x0_female  x0_male  x1_C  x1_S
0  22.0       No        0.0      1.0   0.0   1.0
1  38.0      Yes        1.0      0.0   1.0   0.0
2  26.0      Yes        1.0      0.0   0.0   1.0
3  35.0      Yes        1.0      0.0   0.0   1.0

# 特征工程之特征选择

In [32]:
from sklearn.feature_selection import VarianceThreshold

In [24]:
data_digit = pd.read_csv('/home/lewin/GitHub项目本地存储库/DRL算法实现/Dataset/DigitRecognizer/train.csv', sep=',')

In [25]:
data_digit.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [28]:
data_digit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [29]:
#分离标签和特征
X = data_digit.iloc[:, 1:]
y = data_digit.iloc[:, 0]

## 方差过滤

In [33]:
#零方差过滤
X_var = VarianceThreshold().fit_transform(X)

In [35]:
pd.DataFrame(X_var).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 708 entries, 0 to 707
dtypes: int64(708)
memory usage: 226.9 MB


In [40]:
#所有特征的方差中位数进行方差过滤
np.median(X.values.var(axis=0))
X_medi= VarianceThreshold(np.median(X.values.var(axis=0))).fit_transform(X)


In [41]:
pd.DataFrame(X_medi).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 392 entries, 0 to 391
dtypes: int64(392)
memory usage: 125.6 MB


## 相关性过滤（卡方过滤）

In [42]:
from sklearn.feature_selection import chi2, SelectKBest

In [45]:
#这种手动选择k值的方法可能导致某些有用的特征被剔除掉
X_chi = SelectKBest(chi2, k=300).fit_transform(X_medi, y)

In [47]:
X_chi.shape

(42000, 300)

In [49]:
#可以才用卡方的p值
chiValue, pValue = chi2(X_medi, y)
k = X_medi.shape[1] - (pValue > 0.05).sum()
k


392

In [50]:
X_chi = SelectKBest(chi2, k=k).fit_transform(X_medi, y)

In [52]:
X_chi.shape

(42000, 392)

## F检验

In [54]:
from sklearn.feature_selection import f_classif
#适用于标签是离散的情况
from sklearn.feature_selection import f_regression


In [58]:
f_stat, p_value = f_classif(X_medi, y)
k = X_medi.shape[1] - (p_value > 0.05).sum()

In [59]:
k

392

## 互信息法

In [61]:
#可以用来捕捉标签和特征之间任意的关系
from sklearn.feature_selection import mutual_info_classif as MIC


In [62]:
MIC(X_medi, y)

array([0.06627594, 0.08936422, 0.09715909, 0.11170162, 0.1119075 ,
       0.10766091, 0.08090343, 0.05643799, 0.07103762, 0.09632846,
       0.11561484, 0.14015576, 0.15965559, 0.16741928, 0.14948657,
       0.12723224, 0.09597588, 0.0674488 , 0.03824537, 0.02414672,
       0.06463499, 0.0924372 , 0.11768683, 0.14734507, 0.17295661,
       0.20827838, 0.22146634, 0.23549619, 0.22259258, 0.17339512,
       0.14003095, 0.09814429, 0.07420547, 0.06174511, 0.04494787,
       0.03039705, 0.0554076 , 0.07955366, 0.10191211, 0.12019252,
       0.13730289, 0.14160877, 0.16178321, 0.17951735, 0.18598608,
       0.17510201, 0.15278078, 0.1240899 , 0.10866398, 0.09409223,
       0.08102086, 0.07046496, 0.06136221, 0.04457615, 0.05860998,
       0.07217287, 0.08420771, 0.09209831, 0.10616584, 0.11074446,
       0.10569482, 0.11275603, 0.12465535, 0.11431855, 0.10869245,
       0.12109536, 0.11536525, 0.11401761, 0.09719455, 0.08098477,
       0.07610811, 0.04847603, 0.05164045, 0.06640994, 0.08009